#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countApplesAndOranges function below.
def countApplesAndOranges(s, t, a, b, apples, oranges):
    final_apple = 0
    final_orange = 0

    cal_dist_apple = []
    cal_dist_orange = []
    for i in range(len(oranges)):
        cal = oranges[i] + b
        cal_dist_orange.append(cal)

    for i in range(len(apples)):
        cal = apples[i] + a
        cal_dist_apple.append(cal)


    for i in cal_dist_apple:

        if i >= s and i <= t:
            final_apple = final_apple + 1
        else:
            final_apple = final_apple


    for i in cal_dist_orange:

        if i >= s and i <= t:
            final_orange = final_orange + 1
        else:
            final_orange = final_orange

    final_list=[]
    final_list.append(final_apple)
    final_list.append(final_orange)

    return print(*final_list, sep = "\n")
if __name__ == '__main__':
    st = input().split()

    s = int(st[0])

    t = int(st[1])

    ab = input().split()

    a = int(ab[0])

    b = int(ab[1])

    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
