#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores):
    mini=scores[0]
    maxi=scores[0]
    minc=0
    maxc=0

    for i in range(len(scores)):
        if scores[i]>maxi:
            maxi=scores[i]
            maxc=maxc+1
        if scores[i]<mini:
            mini=scores[i]
            minc=minc+1
    return(maxc,minc)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
