#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the compareTriplets function below.
def compareTriplets(a, b):
    alice=0
    bob=0
    points=[alice,bob]
    for i in range(len(a)):
        if a[i]>b[i]:
            points.pop(0)
            alice=alice+1
            points.insert(0,alice)
        elif a[i]<b[i]:
            points.pop(1)
            bob=bob+1
            points.insert(1,bob)
        elif a[i]==b[i]:
            None


    return points


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
