#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the kangaroo function below.
def kangaroo(x1, v1, x2, v2):
    x1list=[0]
    x2list=[0]

    for i in range(10000):
        x1=x1+v1
        x1list.pop(0)
        x1list.append(x1)


        x2 = x2 + v2
        x2list.pop(0)
        x2list.append(x2)

        if x1list == x2list:
            s = "YES"
            break

        else:
            s = "NO"
            continue

    return s

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    x1V1X2V2 = input().split()

    x1 = int(x1V1X2V2[0])

    v1 = int(x1V1X2V2[1])

    x2 = int(x1V1X2V2[2])

    v2 = int(x1V1X2V2[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + '\n')

    fptr.close()
