#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(mylist):
    # Write your code here
    freq=[0]*100
    for i in range(len(mylist)):
        freq[mylist[i]]=freq[mylist[i]]+1


    ans=[]
    for i in range(1,100):
        ans.append(freq[i]+freq[i-1])
    return max(ans)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
