#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sumXor function below.
def sumXor(n):

    sum = 0
    if n!=0:
        n=str(bin(n))
        for i in range(len(n)):
            if n[i]=='0':
             sum = sum + 1
        return 2**(sum-1)
    else:
        return 1
     

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    result = sumXor(n)

    fptr.write(str(result) + '\n')

    fptr.close()
